pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '5', daysToKeepStr: '10'))
        //disableConcurrentBuilds()
    }
    stages {
        stage('Build') {
            steps {
                sh '/usr/local/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/usr/local/bin/mvn test'
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('local') {
                    sh '/usr/local/bin/mvn clean package -Dsonar.projectKey=demo1 -Dsonar.projectName=demo1 -Dsonar.projectDescription="New Project for Demo" sonar:sonar'
                    } // submitted SonarQube taskId is automatically attached to the pipeline context
            }
        }
         stage('Sonar Quality Gate') {
             steps {		                 
                    script {
                        //sleep 180
                        timeout(time: 30, unit: 'SECONDS') {
                            def qg = waitForQualityGate()
                                    if (!(qg.status == 'OK' || qg.status == 'WARN')) {
                                        error "Pipeline aborted due to quality gate failure: ${qg.status}"
                                    }
                        }
                    }
             }
         }
   }
        
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
}
