pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/usr/local/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/usr/local/bin/mvn test'
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv('local') {
                    sh '/usr/local/bin/mvn clean package sonar:sonar'
                    } // submitted SonarQube taskId is automatically attached to the pipeline context
            }
        }
        stage ("SonarQube Gatekeeper") {
            steps {
                script {
                      def qualitygate = waitForQualityGate()
                          if (qualitygate.status != "OK") {
                             error "Pipeline aborted due to quality gate coverage failure: ${qualitygate.status}"
                          } 
                    }
                 }
       }
   }
        
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
}
